### ISSUE TITLE
作成したテキストをHTMLに挿入してください。

### ISSUE THREAD

**Issue by s1f10220294** [s1f10220294/team-project#7]
僕がそれぞれHTMLファイルをつくっておいたので、そこに作成してもっらたテキストを挿入してください。
あくまでプロトタイプとしてつくったので、細かいHTMLの書き方など、どんどん変更してもらってかまいません

**Comment by s1F102200468** [comment]
完了しました。

**Comment by s1f10220294** [comment]
確認しました。
ありがとうございます
